### ISSUE TITLE
not supported by Titanium SDK 6.0.0

### ISSUE THREAD

**Issue by nascado** [acktie/Acktie-Mobile-Android-QR-Reader#17]
Compilation with the new SDK is not posible. Has anyone an idea how to solve this?

**Comment by mandelmonkey** [comment]
The dev needs to rebuild it for sdk 6.0.0, it doesnt take long so I ope they can do it soon

**Comment by mandelmonkey** [comment]
@nascado if you still need a qr-reader that works in ti6 android let me know I found a working alternative

**Comment by nascado** [comment]
@chris41188  Yes the problem still exists. If you have a solution or a tip, please help.

**Comment by mandelmonkey** [comment]
@nascado I updated the acktie bardcode module to accept qrcode, so you can use this

https://ufile.io/8c426

just unzip and place in your modules android folder

and follow the example found here
https://github.com/acktie/Acktie-Mobile-Barcode-Example

**Comment by nascado** [comment]
Thanks, i was able to complie and scan. But the result is not the QR code.
success(data) gives:
Ti.API.info('Success called with barcode: ' + data.data + ' type: ' + data.type);
> Success called with barcode: 0112590516028223 type: DataBar
Do I have to add another option (? type) ?

**Comment by mandelmonkey** [comment]
I could scan qrcode correctly

when you set up the reader, I changed the ALL variable to this

// All supported Barcode types
var ALL = ["QRCODE"];

so it will only scan qrcodes not barcodes

**Comment by nascado** [comment]
Thanks so much, it worked!!

**Comment by mandelmonkey** [comment]
No worries I find you have to zoom in closer then the overlay grid so I
would remove that

2016/11/30 20:44 "nascado" <notifications@github.com>:
