### ISSUE TITLE
Autofocus problem

### ISSUE THREAD

**Issue by milgner** [acktie/Acktie-Mobile-Android-QR-Reader#2]
Looks like there's still something fishy going on with the autofocus.
After stopping the reader, sometimes this happens:

```
E/AndroidRuntime(22827): java.lang.RuntimeException: Method called after release()
E/AndroidRuntime(22827): 	at android.hardware.Camera.native_autoFocus(Native Method)
E/AndroidRuntime(22827): 	at android.hardware.Camera.autoFocus(Camera.java:1299)
E/AndroidRuntime(22827): 	at com.acktie.mobile.android.camera.CameraManager$2.run(CameraManager.java:232)
E/AndroidRuntime(22827): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(22827): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(22827): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(22827): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime(22827): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22827): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(22827): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
E/AndroidRuntime(22827): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by milgner** [comment]
FYI: I also encountered a crash where it said `java.lang.RuntimeException: autoFocus failed
at android.hardware.Camera.native_autoFocus` but this happened only once and I haven't been able to reproduce it since.

**Comment by milgner** [comment]
Would it be ok for you to publish the source of `acktie-scanner-1.1-SNAPSHOT.jar`, too? Then I may be able to author and test a fix for this problem.

**Comment by TNuzzi** [comment]
@milgner The source is in this project: https://github.com/acktie/Acktie-Zbar-Android

**Comment by milgner** [comment]
Ah, thank you! I'll give it a shot then.

**Comment by milgner** [comment]
The autofocus problem has been resolved with the last changes.

**Comment by ydeshayes** [comment]
Can we have a release ?

**Comment by milgner** [comment]
I have added a [pre-release on our fork](https://github.com/evopark/Acktie-Mobile-Android-QR-Reader/releases/tag/v2.0).
If you could give it a spin I'd appreciate it, but I fear that there may be some regression because the previous version of acktie/Acktie-Zbar-Android (1.0) was not up-to-date with the bundled version in this repository (1.1-SNAPSHOT) - see #4 
Feel free to [open issues](https://github.com/evopark/Acktie-Mobile-Android-QR-Reader/issues) if you encounter any problems, though.

**Comment by ydeshayes** [comment]
Thanks !

**Comment by maximilianmessing** [comment]
@ydeshayes Did you notice any regressions with that release? @TNuzzi Did you check if there were any local changes in your repository that still need merging with the current version?

**Comment by ydeshayes** [comment]
No everything work fine, but if I close my app when the plugin is scanning, and I reopen the app, the screen is black and I can't scan, I've got to close and reopen the scanner. And when I scan a QRcode the pluging freeze with the image of the qr and I need to reopen the scan to continue scanning (I read that you are already aware of this probem but it is a problem for me that avoid me to use it in prod).

**Comment by milgner** [comment]
Yes, the freezing is still a problem. My guess would be that the black screen and the stuck one are actually the same issue: the OS is supposed to update a screen buffer with the camera image but stops at some point. Closing/reopening reinitializes to zero, resulting in a black window. I'm no Android expert by any means, though, so it's just a guess.
I haven't been able to isolate the issue yet, but knowing that it also occurs on other devices helps already. Maybe @TNuzzi has an idea why this is happening?

**Comment by maximilianmessing** [comment]
Would be awesome to get it into production!

**Comment by TNuzzi** [comment]
@maximilianmessing I have no local changes they are all checked in.
@milgner I have had such a problem with the Android camera.  It gets worse because each phone manufacture has a different implementation.  For example HTC initializes the camera in an odd order that could result in a null pointer.  Is the issue you are having on the simulator or on a device?

**Comment by milgner** [comment]
@TNuzzi thanks for the info. I was just wondering because, as documented in #4, the acktie-zbar-android library used to have version 1.1-SNAPSHOT in this repository but was only 1.0-SNAPSHOT in the Github sources. There were interface mismatches, too, so I assumed that you must have made local changes to get it to compile and, along with that, maybe something to fix these bugs I mentioned.

The freezing occurs on an actual device (Samsung Galaxy S5), haven't tested it with a simulator yet. Unfortunately I haven't found a way to connect a real Java debugger to the app, so the only way to debug this is by outputting a lot of log statements: debugging like it's1999... :crying_cat_face:

**Comment by milgner** [comment]
@ydeshayes FYI: since I wasn't able to resolve the problem, I wrote a new QR code scanner from scratch. You can find it at [evopark/tiqr-android](https://github.com/evopark/tiqr-android/).

**Comment by Maninderb87** [comment]
Hi Milgner,
              Can you help with the module which has autofocus problem resolved ?

**Comment by milgner** [comment]
@Maninderb87 as I wasn't able to resolve the problem in this module, I can only help if you're using [evopark/tiqr-android](https://github.com/evopark/tiqr-android) and experiencing problems with that module. The only drawback is that you need different modules for Android and iOS and thus separate, slightly different code paths.

**Comment by Maninderb87** [comment]
Hello @milgner,
                     Even I tried creating the acktie-scanner-1.1-SNAPSHOT.jar with the changes suggested by u in the issue referenced on feb 18 but had no luck as I m unsure that the jar file created correctly, but
I will more than happy to use the evopark/tiqr-android.
Just to give a brief of what i did yesterday with evopark/tiqr-android. I pulled the source code of evopark/tiqr-android into Titanium as I am creating a module in Titanium IDE. However I could not find the module require("de.evopark.tiqr") and the structure of the source code appears to be different.
So can u help me with the creation of module ???

**Comment by Maninderb87** [comment]
@milgner Please reply.
